name: Continuous Delivery

on:
  push:
    branches:
      - main
  release:
    types: [published]

  workflow_dispatch:
    
jobs:
  build_and_deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit
